DELETE http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRyYWdvbnB1bmNoIiwiaWQiOiI2MGE5YmM5ZWUxMjhjNjA1ODg1YzhmNTMiLCJpYXQiOjE2MjE3ODg5NzR9.raLyTOwc1U9wYw3cVlo9OVc_LOudxh8Aragjz9a2Kuc

{
    "blogID": "60a9d7a781159b134467d502"
}
